% acquired_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! acquired_by(Artist, Buyer)
% Relates an artist to an organisation that purchased some of their work.
acquired_by(david_hall, arts_council).
acquired_by(david_hall, british_council).
