% acquired_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
acquired_by(david_hall, arts_council).
acquired_by(david_hall, british_council).
