% active_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! active_in(Person, Project)
% Relates a person to a campaign or project in which they were actively involved.
active_in(mike_stubbs, miners_campaign_tapes).
