% affiliated_with facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
affiliated_with(anna_ridley, analogue).
affiliated_with(david_critchley, acme_housing_association).
affiliated_with(david_critchley, acme).
affiliated_with(david_critchley, birmingham_film_coop).
affiliated_with(david_critchley, brighton).
affiliated_with(david_critchley, coventry).
affiliated_with(david_critchley, film_makers_coop).
affiliated_with(david_critchley, london_video_arts).
affiliated_with(david_critchley, norwich_film_coop).
affiliated_with(david_critchley, royal_college).
affiliated_with(david_critchley, wolverhampton).
affiliated_with(de_appel_foundation, franklin_furnace).
affiliated_with(elsa, jan_van_eyck_academy).
affiliated_with(jan_van_eyck_academy, maastricht).
affiliated_with(lesley_greene, public_art_department_trust).
affiliated_with(mike_stubbs, cardiff_art_college).
affiliated_with(mike_stubbs, granular_synthesis).
affiliated_with(mike_stubbs, hull_time_based_arts).
affiliated_with(mike_stubbs, man_act).
affiliated_with(mike_stubbs, werkleitz_gesellschaft).
affiliated_with(peter_donebauer, diverse).
affiliated_with(peter_donebauer, royal_college_of_art).
affiliated_with(richard_monkhouse, ems).
affiliated_with(rose_garrard, girls_school_in_bow).
affiliated_with(vivian_lovell, ikon).
affiliated_with(vivian_lovell, public_art_commissions_agency_paca).
