% applied_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! applied_to(Applicant, Funder)
% Relates a person to an organisation they applied to for funding.
applied_to(george_barber, arts_council).
applied_to(george_barber, bfi).
