% approached facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
approached(alistair_macintosh, scottish_television).
approached(david_hall, scottish_television).
