% approached facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! approached(Person, Organisation)
% Relates a person to an organisation they approached with a proposal.
approached(alistair_macintosh, scottish_television).
approached(david_hall, scottish_television).
