% artist_in_residence facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! artist_in_residence(Artist)
% Marks an artist or artist group that has held an artist residency.
artist_in_residence(hooykaas_stansfield).
