% assistant_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! assistant_to(Assistant, Person)
% Relates a person to the person they worked for as an assistant.
assistant_to(elsa_stansfield, john_latham).
