% awarded_grant facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! awarded_grant(Recipient, Funder)
% Relates a person to an organisation that awarded them a grant.
awarded_grant(david_critchley, arts_council).
awarded_grant(david_critchley, northern_arts).
