% awarded_grant facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
awarded_grant(david_critchley, arts_council).
awarded_grant(david_critchley, northern_arts).
