% based_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! based_in(Organisation, Place)
% Relates an organisation to the country or place, given as text, where it is based.
based_in(de_appel_foundation, "Netherlands").
