% became_cameraman facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! became_cameraman(Person)
% Marks a person who became a professional cameraman.
became_cameraman(terry_flaxton).
