% began_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! began_in(Work, Year)
% Records the year in which work on a piece or ongoing project began.
began_in(in_two_minds, @1970).
