% broadcast_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! broadcast_by(Work, Broadcaster)
% Relates a work to the broadcaster or station that transmitted it.
broadcast_by(lighthouse, community_radio).
