% chairman_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! chairman_of(Person, Organisation)
% Relates a person to an organisation they chaired.
chairman_of(rose_garrard, malvern_spa_association).
