% co_edited_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! co_edited_by(Publication, Editor, CoEditor)
% Relates a publication to two people who co-edited it.
co_edited_by(special_video_art_issue_may_1976, david_hall, richard_cork).
