% collaborated_with facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
collaborated_with(kevin_atherton, alison_winckle).
collaborated_with(kevin_atherton, audio_arts).
collaborated_with(kevin_atherton, bill_furlong).
collaborated_with(kevin_atherton, dave_critchley).
collaborated_with(kevin_atherton, dave_hanson).
collaborated_with(kevin_atherton, david_hall).
collaborated_with(kevin_atherton, josine_van_drofelaar).
collaborated_with(kevin_atherton, martin_hearne).
collaborated_with(kevin_atherton, mick_duckworth).
collaborated_with(kevin_atherton, peter_kardia).
collaborated_with(kevin_atherton, stephen_partridge).
collaborated_with(kevin_atherton, vivian_lovell).
collaborated_with(kevin_atherton, weis_smals).
