% collaborated_with facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
collaborated_with(de_appel_foundation, franklin_furnace).
collaborated_with(elsa_stansfield, brian_hodgeson).
collaborated_with(elsa_stansfield, delia_derbyshire).
collaborated_with(elsa_stansfield, madelon_hooykaas).
collaborated_with(jan_van_eyck_academy, bridget_riley).
collaborated_with(jan_van_eyck_academy, joan_jonas).
collaborated_with(jan_van_eyck_academy, marina_abramovich).
collaborated_with(jan_van_eyck_academy, ulrike_rosenbach).
collaborated_with(kevin_atherton, alison_winckle).
collaborated_with(kevin_atherton, audio_arts).
collaborated_with(kevin_atherton, bill_furlong).
collaborated_with(kevin_atherton, dave_critchley).
collaborated_with(kevin_atherton, dave_hanson).
collaborated_with(kevin_atherton, david_hall).
collaborated_with(kevin_atherton, josine_van_drofelaar).
collaborated_with(kevin_atherton, martin_hearne).
collaborated_with(kevin_atherton, mick_duckworth).
collaborated_with(kevin_atherton, peter_kardia).
collaborated_with(kevin_atherton, stephen_partridge).
collaborated_with(kevin_atherton, vivian_lovell).
collaborated_with(kevin_atherton, weis_smals).
collaborated_with(madelon_hooykaas, brian_hodgeson).
collaborated_with(madelon_hooykaas, chantal_dupont).
collaborated_with(madelon_hooykaas, david_hall).
collaborated_with(madelon_hooykaas, delia_derbyshire).
collaborated_with(madelon_hooykaas, elsa_stansfield).
collaborated_with(madelon_hooykaas, elsa).
collaborated_with(madelon_hooykaas, frances_marie_uitti).
collaborated_with(madelon_hooykaas, luis_andrews).
collaborated_with(madelon_hooykaas, nam_june_paik).
collaborated_with(montevideo, institute_of_cultural_heritage_in_the_netherlands).
