% commissioning_editor_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! commissioning_editor_for(Person, Broadcaster)
% Relates a person to the broadcaster for which they were a commissioning editor.
commissioning_editor_for(waldemar_januszczak, channel_4).
