% commissioning_editor_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
commissioning_editor_for(waldemar_januszczak, channel_4).
