% conserved_in_project facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! conserved_in_project(Work, Project)
% Relates a work to a conservation project that included it.
conserved_in_project(inside_outside, european_conservation_project).
