% contains_photograph_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! contains_photograph_of(Work, Subject)
% Relates a work to a free-text description of a subject photographed in it.
contains_photograph_of(electron, "fly in amber").
contains_photograph_of(electron, "lizard in amber").
