% contributed_text facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! contributed_text(Author, Publication)
% Relates a person to a publication, such as a catalogue, for which they wrote text.
contributed_text(josine_van_droffelaar, audio_video_installations_catalogue).
