% country_represented facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! country_represented(Work, Country)
% Relates a work to the country, given as text, that it represented at an international exhibition.
country_represented(flying_time, "Netherlands").
