% council_member_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! council_member_of(Person, Organisation)
% Relates a person to an organisation on whose council of management they served.
council_member_of(judith_goddard, london_video_arts).
