% created_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
created_by(an_audience_s_new_clothes, kevin_atherton).
created_by(another_sphere, kevin_atherton).
created_by(any_questions, kevin_atherton).
created_by(brixton_pieces, kevin_atherton).
created_by(gallery_guide, kevin_atherton).
created_by(in_two_minds, kevin_atherton).
created_by(tape_tape, kevin_atherton).
created_by(television_interview, kevin_atherton).
created_by(the_eleventh_hour, kevin_atherton).
created_by(the_tape, kevin_atherton).
created_by(three_minute_16_millimetre_film_of_kevin_atherton_as_a_boxer, kevin_atherton).
created_by(video_times, kevin_atherton).
