% curated_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
curated_by(about_time_at_the_ica_1980, rose_garrard).
curated_by(great_malvern, rose_garrard).
curated_by(locations_edinburgh, alistair_macintosh).
curated_by(luminous_image_show, elsa_stansfield).
curated_by(museum_of_the_20th_century_vienna, rose_garrard).
curated_by(one_artist_one_day, richard_hamilton).
curated_by(pieces_i_never_did, helen_chadwick).
curated_by(reservoir, michael_opray).
curated_by(rose_garrard, helen_chadwick).
curated_by(rose_garrard, three_county_showground).
curated_by(scratch_video_volume_1, george_barber).
curated_by(scratch_video_volume_2, george_barber).
curated_by(show_at_whitechapel_art_gallery, jasia_reichardt).
curated_by(signs_of_the_times, chrissie_isles).
curated_by(stedelijk_museum, dorine_mignot).
curated_by(this_is_a_television_receiver, mark_kidel).
curated_by(whitechapel_art_gallery, jasia_reichardt).
