% curated_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
curated_by(locations_edinburgh, alistair_macintosh).
curated_by(luminous_image_show, elsa_stansfield).
curated_by(one_artist_one_day, richard_hamilton).
curated_by(show_at_whitechapel_art_gallery, jasia_reichardt).
curated_by(stedelijk_museum, dorine_mignot).
curated_by(this_is_a_television_receiver, mark_kidel).
curated_by(whitechapel_art_gallery, jasia_reichardt).
