% department_name facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! department_name(Institution, Name)
% Records the name, given as text, of a department within an institution.
department_name(jan_van_eyck_academy, "Time-Based Art").
