% director_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! director_of(Person, Institution)
% Relates a person to an institution they directed.
director_of(nick_serota, museum_of_modern_art_oxford).
director_of(nick_serota, whitechapel).
