% director_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
director_of(nick_serota, museum_of_modern_art_oxford).
director_of(nick_serota, whitechapel).
