% distributed_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! distributed_by(WorkOrArtist, Distributor)
% Relates a work, or an artist's body of work, to the organisation that distributed it.
distributed_by(between_the_lines, london_video_arts).
distributed_by(judith_goddard, london_video_arts_lva).
distributed_by(time_spent, lva).
