% document facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
document(rewind_david_critchley_interview).
document(rewind_david_hall_interview).
document(rewind_george_barber_interview).
document(rewind_judith_goddard_interview).
document(rewind_kevin_atherton_interview).
document(rewind_madelon_hooykaas_interview).
document(rewind_mike_stubbs_interview).
document(rewind_rose_garrard_interview).
