% documented_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! documented_by(Work, Documenter)
% Relates a work to a person who made a video documentation of it.
documented_by(video_document, anna_ridley).
