% duration_minutes facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! duration_minutes(Work, Minutes)
% Records the running time of a work in minutes.
duration_minutes(one_of_these_days, 30).
duration_minutes(running_time_1979, 6).
