% duration_minutes facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
duration_minutes(one_of_these_days, 30).
duration_minutes(running_time_1979, 6).
