% edited_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
edited_at(all_the_pieces_i_never_did, fantasy_factory).
edited_at(david_hall, studio_in_penicuik).
edited_at(one_of_these_days, neils_yard_covent_garden).
