% educated_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
educated_at(dave_hanson, leeds).
educated_at(david_critchley, newcastle_likely_newcastle_university).
educated_at(david_critchley, newcastle_polytechnic).
educated_at(david_critchley, royal_college).
educated_at(david_dye, saint_martins).
educated_at(david_hall, royal_college).
educated_at(elsa_stansfield, ealing_school).
educated_at(elsa_stansfield, glasgow_art_school).
educated_at(elsa_stansfield, glasgow_school_of_art).
educated_at(elsa_stansfield, slade_school_of_art).
educated_at(george_barber, slade).
educated_at(george_barber, st_martins).
educated_at(judith_goddard, royal_college).
educated_at(kevin_atherton, leeds_college_of_art).
educated_at(mike_stubbs, cardiff_art_college).
educated_at(mike_stubbs, royal_college_of_art).
educated_at(rose_garrard, birmingham_college_of_art).
educated_at(rose_garrard, chelsea).
educated_at(rose_garrard, stourbridge_college).
educated_at(tony_hill, saint_martins).
