% employed_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
employed_by(kevin_atherton, cardiff).
employed_by(kevin_atherton, chelsea).
employed_by(kevin_atherton, maidstone).
employed_by(kevin_atherton, middlesex).
employed_by(kevin_atherton, museum_of_modern_art_oxford).
employed_by(kevin_atherton, national_college_of_art_and_design_dublin).
employed_by(kevin_atherton, royal_college_of_art).
employed_by(kevin_atherton, slade).
employed_by(kevin_atherton, whitechapel).
