% established facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
established(kevin_atherton, ma_virtual_realities).
established(kevin_atherton, virtual_realities_as_fine_art_medium).
