% established_programme facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! established_programme(Person, Programme)
% Relates a person to the name, given as text, of an academic programme they set up.
established_programme(david_hall, "Film, Video and Sound").
