% event facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! event(Event)
% Marks an entity as an event, such as a festival or tour.
event(edinburgh_television_festival).
event(pop_tour).
