% exhibition_title facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! exhibition_title(Exhibition, Title)
% Records the title of an exhibition or exhibition series as text.
exhibition_title(the_video_stairs, "The Video Stairs").
