% exhibition facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
exhibition(british_art_show_ii).
exhibition(british_art_show).
exhibition(herbert_art_gallery_video_show_1970s).
exhibition(one_artist_one_day).
exhibition(un_certain_art_anglais).
