% exhibited_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
exhibited_at(an_audience_s_new_clothes, musee_d_art_moderne).
exhibited_at(an_audience_s_new_clothes, un_certain_art_anglais).
exhibited_at(coronation_street_piece, british_art_show).
exhibited_at(kevin_atherton, acme_gallery).
exhibited_at(kevin_atherton, air_gallery).
exhibited_at(kevin_atherton, rosemary_gallery).
exhibited_at(kevin_atherton, un_certain_art_anglais).
exhibited_at(one_artist_one_day, angela_flowers_gallery).
exhibited_at(television_interview, british_art_show_ii).
exhibited_at(television_interview, edinburgh).
exhibited_at(television_interview, ikon_gallery_birmingham).
exhibited_at(television_interview, southampton).
exhibited_at(video_times, ikon_gallery_birmingham).
