% exhibition facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
exhibition(ave_festival_in_holland).
exhibition(baltic).
exhibition(british_art_show_ii).
exhibition(british_art_show).
exhibition(burning_bush).
exhibition(herbert_art_gallery_video_show_1970s).
exhibition(london_film_festival).
exhibition(luminous_image_show).
exhibition(luminous_image).
exhibition(montreal_videotapes_retrospective_1988).
exhibition(netherlands_representation_in_south_korea_2005).
exhibition(not_just_another_art_show).
exhibition(one_artist_one_day).
exhibition(pompidou_show).
exhibition(retrospective_festivals).
exhibition(river_crossings_with_camerawork).
exhibition(root_festival).
exhibition(show_at_de_appel_foundation).
exhibition(show_at_whitechapel_art_gallery).
exhibition(sidney_biennale).
exhibition(the_video_stairs).
exhibition(un_certain_art_anglais).
exhibition(video_manifestation).
exhibition(video_sculpture_show_in_germany).
