% external_examiner_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
external_examiner_at(rose_garrard, belfast).
external_examiner_at(rose_garrard, newcastle).
external_examiner_at(rose_garrard, slade_school_of_fine_art).
external_examiner_at(rose_garrard, the_royal_college).
