% featured_person facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! featured_person(Work, Description)
% Relates a work to a free-text description of a person or figure who appears in it.
featured_person(running_time_1979, "figure running in the landscape").
