% filmed_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! filmed_at(Work, Location)
% Relates a work to a location where its footage was filmed.
filmed_at(brewing, hook_norton_brewery).
filmed_at(motion_parallax, richmond_park).
