% financed_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
financed_by(elsa_stansfield, "project by project funding, galleries, sound work in Industry, commercials").
financed_by(madelon_hooykaas, "project by project funding, galleries, sales of silk-screens").
