% first_used_technique facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! first_used_technique(Work, Technique)
% Relates a work to a technique, given as text, that its artists used for the first time in it.
first_used_technique(flying_time, "editing").
