% first_shown_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! first_shown_at(Work, Venue)
% Relates a work to the venue where it was first shown.
first_shown_at(reservoir, john_hansard_gallery).
