% first_exhibition_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
first_exhibition_of(the_video_stairs, hooykaas_stansfield).
