% first_exhibition_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! first_exhibition_of(Exhibition, Artist)
% Relates an exhibition space or programme to the artist or group who had its first exhibition.
first_exhibition_of(the_video_stairs, hooykaas_stansfield).
