% founded_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
founded_by(association_of_video_artists_in_the_netherlands, elsa_stansfield).
founded_by(association_of_video_artists_in_the_netherlands, madelon_hooykaas).
