% funded_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
funded_by(between_the_lines, girls_school_in_bow).
funded_by(david_critchley, arts_council).
funded_by(david_hall, arts_council).
funded_by(david_hall, british_council).
funded_by(deep_looking, buddhist_broadcasting_foundation).
funded_by(film_and_video_umbrella, arts_council).
funded_by(george_barber, royal_college_of_art).
funded_by(judith_goddard, arts_council).
funded_by(kevin_atherton, arts_council_of_great_britain).
funded_by(london_video_arts_lva, arts_council).
funded_by(london_video_arts_lva, channel_4).
funded_by(london_video_arts_lva, greater_london_council_glc).
funded_by(london_video_arts_lva, gulbenkian_foundation).
funded_by(london_video_arts, arts_council).
funded_by(lva_london_video_arts, arts_council).
funded_by(malvern_well_dressing_festival, arts_council).
funded_by(mike_stubbs, arts_council).
funded_by(mike_stubbs, bbc).
funded_by(mike_stubbs, channel_4).
funded_by(mike_stubbs, s4c).
funded_by(peter_donebauer, arts_council).
funded_by(peter_donebauer, bbc).
funded_by(peter_donebauer, bfi).
funded_by(peter_donebauer, british_film_institute_bfi).
funded_by(peter_donebauer, diverse).
funded_by(peter_donebauer, emi).
funded_by(peter_donebauer, gulbenkian_foundation).
funded_by(pharmacopoeia, wellcome_foundation).
funded_by(revision, buddhist_broadcasting_foundation).
funded_by(taxi_driver_ii, channel_4).
funded_by(television_circle_electron, tswa3d_project).
funded_by(the_starless_cast, chapter_art_centre).
funded_by(venetian_ghost, channel_4).
funded_by(vertical, arts_council).
funded_by(vi_deo_volente, de_appel).
