% funded_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
funded_by(deep_looking, buddhist_broadcasting_foundation).
funded_by(kevin_atherton, arts_council_of_great_britain).
funded_by(revision, buddhist_broadcasting_foundation).
funded_by(vi_deo_volente, de_appel).
