% gave_exhibition_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
gave_exhibition_to(gallery_in_bremen, hooykaas_stansfield).
