% gave_exhibition_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! gave_exhibition_to(Venue, Artist)
% Relates a venue to an artist or group to whom it gave an exhibition.
gave_exhibition_to(gallery_in_bremen, hooykaas_stansfield).
