% had_machine_made_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! had_machine_made_by(Work, Maker)
% Relates a work to the person who built a machine used in it.
had_machine_made_by(reservoir, john_wall).
