% head_of_department facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! head_of_department(Person, Department)
% Relates a person to a department they headed.
head_of_department(kevin_atherton, fine_art_media_department).
