% held_position facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! held_position(Person, Position)
% Relates a person to a job title, given as text, that they held.
held_position(kevin_atherton, "Head of Department").
