% held_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! held_at(Event, Venue)
% Relates an exhibition or event to the venue or institution where it was held.
held_at(video_manifestation, jan_van_eyck_academy).
