% idea_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! idea_for(SourceWork, LaterWork)
% Relates a work to a later work for which it provided the idea.
idea_for(video_document, iron_horses).
