% in_collection_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
in_collection_of(from_the_museum_of_memory, stedelijk_museum_amsterdam).
