% in_collection facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
in_collection(museum_of_memory_1, stedelijk_museum_amsterdam).
in_collection(shadow_pictures, stedelijk_museum_amsterdam).
