% in_collection facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! in_collection(Work, Collection)
% Relates a work to the museum or institution whose collection holds it.
in_collection(from_the_museum_of_memory, stedelijk_museum_amsterdam).
in_collection(museum_of_memory_1, stedelijk_museum_amsterdam).
in_collection(shadow_pictures, stedelijk_museum_amsterdam).
