% influenced_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! influenced_by(Artist, Influence)
% Relates an artist to a person who influenced their work.
influenced_by(peter_donebauer, hans_jenning).
influenced_by(peter_donebauer, kandinsky).
influenced_by(peter_donebauer, turner).
