% inspired_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
inspired_by(judith_goddard, t_s_eliot).
inspired_by(judith_goddard, william_blake).
