% installed_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! installed_at(Work, Location)
% Relates a work to the location where it is installed.
installed_at(spout_sculpture, belle_vue_island).
