% interviewed facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! interviewed(Interviewer, Interviewee)
% Relates a person to someone they interviewed, as mentioned in an interview; the source interviews themselves are recorded by interviewee.
interviewed(terry_flaxton, annie_lennox).
interviewed(terry_flaxton, madonna).
