% interviewee facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
interviewee(rewind_anna_ridley_interview, anna_ridley).
interviewee(rewind_david_critchley_interview, david_critchley).
interviewee(rewind_david_hall_interview, david_hall).
interviewee(rewind_george_barber_interview, george_barber).
interviewee(rewind_judith_goddard_interview, judith_goddard).
interviewee(rewind_kevin_atherton_interview, kevin_atherton).
interviewee(rewind_madelon_hooykaas_interview, madelon_hooykaas).
interviewee(rewind_mike_stubbs_interview, mike_stubbs).
interviewee(rewind_peter_donebauer_interview, peter_donebauer).
interviewee(rewind_rose_garrard_interview, rose_garrard).
