% interviewed_artist facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
interviewed_artist(anna_ridley).
interviewed_artist(david_critchley).
interviewed_artist(david_hall).
interviewed_artist(george_barber).
interviewed_artist(judith_goddard).
interviewed_artist(kevin_atherton).
interviewed_artist(madelon_hooykaas).
interviewed_artist(mike_stubbs).
interviewed_artist(peter_donebauer).
interviewed_artist(rose_garrard).
