% invited_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! invited_to(Person, Host)
% Relates a person to an institution or event they were invited to visit or take part in.
invited_to(bridget_riley, jan_van_eyck_academy).
invited_to(david_hall, locations_edinburgh).
invited_to(joan_jonas, jan_van_eyck_academy).
invited_to(john_latham, jan_van_eyck_academy).
invited_to(marina_abramovich, jan_van_eyck_academy).
invited_to(ulrike_rosenbach, jan_van_eyck_academy).
