% invited_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! invited_by(Person, Event)
% Relates a person to an exhibition or event they were invited to take part in; despite the name, the second argument is the event, not the inviter.
invited_by(mick_hartney, video_manifestation).
