% involved_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
involved_in(anna_ridley, video_show_at_the_serpentine_gallery_1975).
involved_in(elsa_stansfield, arts_lab).
