% length_minutes facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! length_minutes(Work, Minutes)
% Records the length of a work in minutes.
length_minutes(running_time, 6).
