% made_proposal_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! made_proposal_to(Person, Organisation)
% Relates a person to an organisation to which they submitted a proposal.
made_proposal_to(rose_garrard, malvern_town_council).
