% made_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
made_at(kevin_atherton, amsterdam).
made_at(kevin_atherton, de_appel_gallery).
made_at(sphere, ballymun_park_in_dublin).
made_at(tape_tape, battersea_arts_centre).
