% member_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! member_of(Person, Organisation)
% Relates a person to an organisation, union or artistic group they belonged to.
member_of(mike_stubbs, association_of_cinematographic_and_television_technicians).
member_of(robin_page, fluxus).
