% member_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
member_of(mike_stubbs, association_of_cinematographic_and_television_technicians).
member_of(robin_page, fluxus).
