% mentor_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! mentor_of(Mentor, Mentee)
% Relates a mentor to the person they mentored.
mentor_of(parish_chakraborti, peter_donebauer).
