% met_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! met_at(Person, Venue)
% Relates a person to a venue where they met someone; the other person is not recorded.
met_at(david_critchley, serpentine_gallery).
