% mission_statement_created_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! mission_statement_created_for(Organisation, Contributor)
% Relates an organisation to a person who took part in writing its mission statement.
mission_statement_created_for(london_video_arts, david_critchley).
