% music_promotion_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! music_promotion_by(Musician, Promoter)
% Relates a musician or band to a person who promoted their live performances.
music_promotion_by(ali_farka_toure, mike_stubbs).
music_promotion_by(anne_whitehurst, mike_stubbs).
music_promotion_by(bhindu_boys, mike_stubbs).
music_promotion_by(dudu_pakwana, mike_stubbs).
music_promotion_by(remmy_onglala, mike_stubbs).
