% music_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! music_by(Work, Composer)
% Relates a work to the person who made its music.
music_by(mandala, mike_ray).
music_by(one_of_these_days, delia_derbyshire).
