% named_by_competition facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! named_by_competition(Work)
% Marks a work whose name was chosen through a public competition.
named_by_competition(malvina_sculpture).
