% organisation facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
organisation(analogue).
organisation(architects_journal).
organisation(art_monthly).
organisation(arts_council_of_great_britain).
organisation(arts_council).
organisation(audio_arts).
organisation(british_council).
organisation(british_rail).
organisation(cardiff).
organisation(channel_4).
organisation(chelsea_college_of_art).
organisation(chelsea).
organisation(dublin).
organisation(fine_art_media_department).
organisation(goldsmiths).
organisation(hornsey_or_middlesex).
organisation(ikon).
organisation(leeds_college_of_art).
organisation(leeds).
organisation(ma_virtual_realities).
organisation(maidstone).
organisation(middlesex).
organisation(national_college_of_art_and_design_dublin).
organisation(national_college_of_art_and_design_in_dublin).
organisation(netherland_1).
organisation(picador).
organisation(public_art_commissions_agency_paca).
organisation(public_art_department_trust).
organisation(rowen_from_the_midlands).
organisation(royal_college_of_art).
organisation(royal_college).
organisation(slade).
organisation(studio_international).
organisation(video_artists_on_tour).
organisation(virtual_realities_as_fine_art_medium).
