% organised_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! organised_by(Event, Organiser)
% Relates an exhibition, event or programme to the person or organisation that organised it.
organised_by(locations_edinburgh, scottish_arts_council).
organised_by(malvern_spa_association, rose_garrard).
organised_by(video_manifestation, elsa_stansfield).
