% original_name_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
original_name_of(association_of_video_artists_in_the_netherlands, foundation_time_based_arts).
