% partner_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! partner_of(Person, Partner)
% Relates a person to their life partner.
partner_of(rita_donagh, richard_hamilton).
