% participated_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! participated_in(Person, Programme)
% Relates a person to a scheme, programme or event they took part in.
participated_in(kevin_atherton, video_artists_on_tour).
