% performed_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
performed_at(kevin_atherton, ayton_basement).
performed_at(kevin_atherton, battersea_arts_centre).
performed_at(kevin_atherton, butlers_wharf).
performed_at(kevin_atherton, de_appel).
performed_at(kevin_atherton, herbert_art_gallery_video_show_1970s).
performed_at(kevin_atherton, musee_d_art_moderne).
performed_at(kevin_atherton, rotterdam).
