% performed_work facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! performed_work(Performer, Work)
% Relates an artist to a performance work they performed.
performed_work(kevin_atherton, an_audience_s_new_clothes).
