% photographed_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! photographed_by(Work, Photographer)
% Relates a work to the person who took photographs used in it.
photographed_by(electron, judith_goddard).
