% president_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
president_of(madelon_hooykaas, association_of_video_artists_in_the_netherlands).
president_of(madelon_hooykaas, time_based_arts_in_amsterdam).
president_of(madelon_hooykaas, time_based_arts).
