% president_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! president_of(Person, Organisation)
% Relates a person to an organisation of which they were president.
president_of(madelon_hooykaas, association_of_video_artists_in_the_netherlands).
president_of(madelon_hooykaas, time_based_arts_in_amsterdam).
president_of(madelon_hooykaas, time_based_arts).
