% produced_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
produced_by(stooky_bill_tv, anna_ridley).
produced_by(this_is_a_television_receiver, anna_ridley).
produced_by(this_is_a_television_receiver, mark_kidel).
