% programmed facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! programmed(Person, Programme)
% Relates a person to the kind of material, given as text, that they selected for a screening programme.
programmed(elsa_stansfield, "films").
