% project_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! project_for(Artist, Client)
% Relates an artist to an organisation for which they made a commissioned project.
project_for(kevin_atherton, netherland_1).
