% promoted_medium facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! promoted_medium(Organisation, Medium)
% Relates an organisation to an artistic medium, given as text, that it actively promoted.
promoted_medium(de_appel_foundation, "video").
