% protagonist_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! protagonist_in(Person, Artist)
% Relates a person to the artist in whose work they appeared as a protagonist.
protagonist_in(ray_reardon, david_mach).
protagonist_in(stephen_hendry, david_mach).
