% provided_soundtrack facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! provided_soundtrack(Work, Composer)
% Relates a work to the person who provided its soundtrack.
provided_soundtrack(one_of_these_days, delia_derbyshire).
