% published_catalogues_of facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! published_catalogues_of(Publisher, Artist)
% Relates a venue or publisher to an artist or group whose work it published catalogues of.
published_catalogues_of(gallery_in_bremen, hooykaas_stansfield).
