% published_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
published_in(serpentine_1975_show, organisation_art_and_artists).
published_in(special_video_art_issue_may_1976, studio_international).
