% published_catalogues_of_work_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
published_catalogues_of_work_by(gallery_in_bremen, hooykaas_stansfield).
