% published_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! published_by(Publication, Publisher)
% Relates a publication or published piece to the organisation or editor responsible for publishing it.
published_by(serpentine_1975_show, organisation_art_and_artists).
published_by(studio_international, richard_cork).
