% ran facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! ran(Person, Activity)
% Relates a person to something, given as text, that they ran or managed.
ran(elsa_stansfield, "cinema at Arts Lab").
ran(elsa_stansfield, "cinema").
