% received_funding_from facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! received_funding_from(Recipient, Funder)
% Relates a person to an organisation from which they received funding.
received_funding_from(george_barber, arts_council).
