% renamed_as facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! renamed_as(FormerOrganisation, LaterOrganisation)
% Relates an organisation to the name or organisation it was later renamed as.
renamed_as(association_of_video_artists_in_the_netherlands, time_based_arts).
