% renamed_as facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
renamed_as(association_of_video_artists_in_the_netherlands, time_based_arts).
