% rented_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! rented_by(Premises, Organisation)
% Relates premises to an organisation involved in renting them; whether it was landlord or tenant is not distinguished.
rented_by(little_newport_street_soho, the_other_cinema).
