% residency_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! residency_at(Artist, Location)
% Relates an artist to a place or venue where they held a residency.
residency_at(rose_garrard, great_malvern).
