% shot_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
shot_in(behind_the_veil, saudi_arabia).
shot_in(running_time_1979, north_of_england).
