% showed_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! showed_at(Work, Venue)
% Relates a work to a venue where it was shown.
showed_at(day_for_night, visual_research_centre_in_dundee_contemporary_arts).
