% sold_work_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! sold_work_to(Artist, Buyer)
% Relates an artist to a buyer, given as text, to whom they sold work.
sold_work_to(hooykaas_stansfield, "a museum").
