% sold_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! sold_at(Work, Retailer)
% Relates a work to a retailer that sold copies of it.
sold_at(the_greatest_hits_of_scratch_video, tower_records).
