% soundtrack_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
soundtrack_by(cultural_quarter, chris_wiltshire).
soundtrack_by(cultural_quarter, david_shea).
soundtrack_by(cultural_quarter, i_dream_of_tall_buildings).
soundtrack_by(cultural_quarter, mark_fell_snd).
soundtrack_by(cultural_quarter, simon_thorne).
soundtrack_by(cultural_quarter, ulf_langheinrich).
soundtrack_by(lighthouse, gerald_mair).
