% source_url facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
source_url(rewind_david_critchley_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/DC503.pdf").
source_url(rewind_david_hall_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/DH510.pdf").
source_url(rewind_george_barber_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/GB510.pdf").
source_url(rewind_kevin_atherton_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/KAT510.pdf").
source_url(rewind_madelon_hooykaas_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/ESMH510.pdf").
source_url(rewind_mike_stubbs_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/MS510.pdf").
source_url(rewind_rose_garrard_interview, "https://rewind.ac.uk/rewind/wp-content/uploads/sites/146/2021/03/RG510.pdf").
