% started_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! started_by(Organisation, Year)
% Records the year in which an organisation was started; despite the name, the second argument is a year, not a founder.
started_by(de_appel_foundation, @1975).
