% studied_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
studied_at(elsa_stansfield, ealing_school).
studied_at(elsa_stansfield, glasgow_art_school).
studied_at(elsa_stansfield, slade_school_of_art).
studied_at(kevin_atherton, leeds_college_of_art).
studied_at(madelon_hooykaas, ealing_school_of_art).
