% supported_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
supported_by(kevin_atherton, anna_ridley).
supported_by(kevin_atherton, josine_van_droffelaar).
supported_by(kevin_atherton, lesley_greene).
supported_by(kevin_atherton, rita_donagh).
supported_by(kevin_atherton, vivian_lovell).
supported_by(kevin_atherton, weis_smals).
