% supported_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! supported_by(Artist, Supporter)
% Relates an artist to a person who supported or championed their career.
supported_by(kevin_atherton, anna_ridley).
supported_by(kevin_atherton, josine_van_droffelaar).
supported_by(kevin_atherton, lesley_greene).
supported_by(kevin_atherton, rita_donagh).
supported_by(kevin_atherton, vivian_lovell).
supported_by(kevin_atherton, weis_smals).
