% taught_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! taught_at(Person, Institution)
% Relates a person to an institution where they taught.
taught_at(david_hall, maidstone_college_of_art).
taught_at(mike_stubbs, dundee).
