% taught_by facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! taught_by(Student, Teacher)
% Relates a student to a person who taught them.
taught_by(david_critchley, stuart_marshall).
