% travelled_to facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! travelled_to(Artist, Place)
% Relates an artist or group to a place, given as text, that they travelled to.
travelled_to(hooykaas_stansfield, "Japan").
