% used_institutional_resource facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_institutional_resource(Person, Institution)
% Relates a person to an institution whose equipment or resources they used.
used_institutional_resource(peter_donebauer, royal_college_of_art).
