% used_in_work facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
used_in_work(field_free_space, faraday_cage).
used_in_work(video_void, wapping_rotherhithe_tunnel).
