% used_technology facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_technology(Person, Technology)
% Relates a person to a technology or device, given as text, that they used.
used_technology(peter_donebauer, "black and white portapak").
used_technology(peter_donebauer, "colour studio").
used_technology(peter_donebauer, "mechanical transducer device").
used_technology(peter_donebauer, "monochrome portapak").
