% used_venue facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_venue(Organisation, Venue)
% Relates an organisation to a venue it used, for example for meetings.
used_venue(hull_time_based_arts, ye_olde_black_boy).
