% used_software facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
used_software(judith_goddard, avid_express_dv).
used_software(judith_goddard, avid).
