% used_editing_equipment_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_editing_equipment_at(Artist, Provider)
% Relates an artist to a company or person whose editing equipment they used.
used_editing_equipment_at(george_barber, flextech).
used_editing_equipment_at(george_barber, terry_flaxton).
