% used_lab facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_lab(Person, Lab)
% Relates a person to a film laboratory they used.
used_lab(david_hall, kays_laboratory_soho).
