% used_medium facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_medium(Work, Medium)
% Relates a work to a medium or format, given as text, used in it.
used_medium(sea_of_light, "videotape").
used_medium(two_sides_of_a_story, "live video").
used_medium(two_sides_of_a_story, "monitors").
