% used_material facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! used_material(Work, Material)
% Relates a work to a physical material, given as text, that it is made from.
used_material(spout_sculpture, "bronze").
used_material(spout_sculpture, "stone").
