% used_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
used_in(day_for_night, "non-linear DVD works using the shuffle method").
used_in(flying_time, "colour").
