% uses_venue facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
uses_venue(reservoir, southampton).
uses_venue(silver_lining, tate_liverpool).
