% uses_venue facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! uses_venue(Work, Venue)
% Relates a work to a venue or place it was commissioned for or shown at.
uses_venue(reservoir, southampton).
uses_venue(silver_lining, tate_liverpool).
