% uses_medium facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
uses_medium(double_vision, "video").
uses_medium(gallery_guide, "performance").
uses_medium(gallery_guide, "video projection").
uses_medium(gallery_guide, "video").
uses_medium(gallery_guide, "virtual reality").
uses_medium(kevin_atherton, "bronze").
uses_medium(kevin_atherton, "sound").
uses_medium(kevin_atherton, "television commercial").
uses_medium(kevin_atherton, "video").
uses_medium(kevin_atherton, "voice").
uses_medium(sphere, "mirror polished-stainless steel").
uses_medium(sphere, "video").
uses_medium(tape_tape, "masking tape").
uses_medium(tape_tape, "videotape").
