% uses_actors facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! uses_actors(Work)
% Marks a work made with actors.
uses_actors(taxi_driver_ii).
uses_actors(venetian_ghost).
