% venue facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
venue(acme_gallery).
venue(air_gallery).
venue(amsterdam).
venue(angela_flowers_gallery).
venue(ayton_basement).
venue(ballymun_park_in_dublin).
venue(battersea_arts_centre).
venue(butlers_wharf).
venue(covent_garden).
venue(de_appel_gallery).
venue(de_appel).
venue(earlham_street).
venue(edinburgh).
venue(garage_gallery).
venue(herbert_art_gallery).
venue(ica_theatre).
venue(ikon_gallery_birmingham).
venue(kettles_yard).
venue(manx_museum).
venue(musee_d_art_moderne).
venue(museum_of_modern_art_oxford).
venue(pmj_self).
venue(rosemary_gallery).
venue(rotterdam).
venue(serpentine_gallery).
venue(southampton).
venue(whitechapel).
