% venue_in_area facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! venue_in_area(Area, Venue)
% Relates an area to a venue located in it; despite the name, the area is the first argument.
venue_in_area(covent_garden, acme_gallery).
venue_in_area(covent_garden, air_gallery).
venue_in_area(covent_garden, garage_gallery).
venue_in_area(covent_garden, pmj_self).
