% work_discussed_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! work_discussed_in(Artist, Publication)
% Relates an artist to a publication, or an organisation's publications, in which their work was discussed.
work_discussed_in(david_critchley, independent_media).
work_discussed_in(david_critchley, readings_magazine).
work_discussed_in(david_critchley, the_kitchen).
