% worked_as facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
worked_as(kevin_atherton, "attendant").
worked_as(kevin_atherton, "technician invigilator").
