% worked_as_assistant_in_city facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! worked_as_assistant_in_city(Person, City)
% Relates a person to a city, given as text, where they worked as an assistant.
worked_as_assistant_in_city(madelon_hooykaas, "Paris").
