% worked_at facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! worked_at(Person, Organisation)
% Relates a person to an organisation or institution where they worked.
worked_at(elsa_stansfield, fantasy_factory).
worked_at(elsa_stansfield, maidstone_college_of_art).
worked_at(josine_van_droffelaar, de_appel_foundation).
worked_at(madelon_hooykaas, fantasy_factory).
worked_at(madelon_hooykaas, maidstone_college_of_art).
