% worked_with_sound facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! worked_with_sound(Artist)
% Marks an artist who has worked with sound.
worked_with_sound(kevin_atherton).
