% work_shown_in facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! work_shown_in(Artist, Institution)
work_shown_in(clive_richardson, royal_college).
