% work facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
work(an_audience_s_new_clothes).
work(another_sphere).
work(any_questions).
work(brixton_pieces).
work(cate_elwes_s_book_video_art_a_guided_tour).
work(coronation_street_piece).
work(deanna_petherbridge_s_book_art_within_reach).
work(double_vision).
work(forest_of_dean_window).
work(gallery_guide).
work(in_two_minds).
work(iron_horses).
work(roselee_goldberg_s_first_edition_of_performance_art).
work(sphere).
work(tape_tape).
work(television_interview).
work(the_big_breakfast_show).
work(the_eleventh_hour).
work(the_tape).
work(three_minute_16_millimetre_film_of_kevin_atherton_as_a_boxer).
work(video_document).
work(video_times).
