% wrote_about facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! wrote_about(Writer, Work)
% Relates a writer to a work they wrote about.
wrote_about(michael_o_pray, scratch_video_volume_1).
wrote_about(sean_cubitt, reservoir).
