% wrote_for facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
wrote_for(david_hall, studio_international).
wrote_for(david_hall, timeout).
