% year_joined facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_joined(Person, Year)
% Records the year in which a person joined an organisation or post; the organisation is not recorded.
year_joined(elsa, @1980).
