% year_involved facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_involved(Person, Organisation, Period)
% Records, as free text, the period in which a person was involved with an organisation.
year_involved(elsa_stansfield, arts_lab, "1967 or 1968").
