% year_travelled facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_travelled(Artist, Year)
% Records a year in which an artist or group travelled; the destination is not recorded.
year_travelled(hooykaas_stansfield, @1984).
