% year_started facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_started(Work, Year)
% Records the year in which work on a piece started.
year_started(public_face_private_eye, @1988).
