% year_started_using_technology facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
year_started_using_technology(peter_donebauer, "colour studio").
year_started_using_technology(peter_donebauer, "portapaks").
