% year_travelled facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
year_travelled(hooykaas_stansfield, @1984).
