% year_started_work facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
year_started_work(elsa_stansfield, jan_van_eyck_academy, @1980).
