% year_exhibited facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_exhibited(Artist, Year)
% Records a year in which an artist exhibited work.
year_exhibited(madelon_hooykaas, @1971).
year_exhibited(madelon_hooykaas, @1972).
