% year_started_using_technology facts generated by beingdb-rewind-interviews (npm run extract).
% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.
% Do not hand-edit generated lines below - regenerate and review the diff instead.
% The %! declaration below is maintained in config/predicate-declarations.json.

%! year_started_using_technology(Person, Technology)
% Relates a person to a technology, given as text, that they started using; despite the name, no year is recorded.
year_started_using_technology(peter_donebauer, "colour studio").
year_started_using_technology(peter_donebauer, "portapaks").
