import * as fs from "node:fs";
import * as path from "node:path";
import type { FactArgument, ResolvedFact } from "./types.js";
import { DECLARATIONS_FILENAME, type PredicateDeclaration, declarationOf, loadDeclarationsFor, renderDeclaration } from "./declarations.js";

/** Renders one typed argument as a BeingDB literal (see docs/query-language.md "Literal types"). */
export function literalToString(arg: FactArgument): string {
  switch (arg.kind) {
    case "atom":
      return arg.value;
    case "string":
      return `"${escapeString(arg.value)}"`;
    case "year":
      return `@${arg.value}`;
    case "integer":
      return String(arg.value);
    case "decimal":
      return arg.value;
    case "boolean":
      return arg.value ? "true" : "false";
  }
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Renders one fact as a single BeingDB proposition line, e.g. `created_by(tape_tape, kevin_atherton).`. */
export function factToProposition(predicate: string, args: FactArgument[]): string {
  return `${predicate}(${args.map(literalToString).join(", ")}).`;
}

const GENERATED_HEADER = (predicate: string) =>
  `% ${predicate} facts generated by beingdb-rewind-interviews (npm run extract).\n` +
  `% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.\n` +
  `% Do not hand-edit generated lines below - regenerate and review the diff instead.\n`;

// The blank line is required: a BeingDB declaration's description is every
// `%` line after `%!`, so the header must not run into it.
const DECLARATION_BLOCK = (predicate: string, declaration: PredicateDeclaration) =>
  `% The %! declaration below is maintained in config/${DECLARATIONS_FILENAME}.\n` +
  `\n` +
  renderDeclaration(predicate, declaration) +
  `\n`;

function isDataLine(line: string): boolean {
  const trimmed = line.trim();
  return trimmed.length > 0 && !trimmed.startsWith("%") && !trimmed.startsWith("#");
}

/** Reads the existing data (non-comment) lines of a predicate file, if any. */
export function readExistingPropositions(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  return fs
    .readFileSync(filePath, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(isDataLine);
}

export interface MergeResult {
  predicate: string;
  file: string;
  addedCount: number;
  totalCount: number;
}

/**
 * Renders the full text of a predicate file: the standard header, then - if
 * config/predicate-declarations.json (next to `predicatesDir`) declares this
 * predicate - its BeingDB `%!` declaration, then the deduplicated, sorted facts.
 */
export function renderPredicateFile(predicatesDir: string, predicate: string, lines: Iterable<string>): string {
  const sorted = Array.from(new Set(lines)).sort((a, b) => a.localeCompare(b));
  const declaration = declarationOf(loadDeclarationsFor(predicatesDir), predicate);
  const header = GENERATED_HEADER(predicate) + (declaration ? DECLARATION_BLOCK(predicate, declaration) : "");
  return header + sorted.join("\n") + "\n";
}

/** Writes a predicate's complete proposition set (see {@link renderPredicateFile}). */
export function writePropositions(predicatesDir: string, predicate: string, lines: Iterable<string>): string {
  const filePath = path.join(predicatesDir, `${predicate}.pl`);
  const content = renderPredicateFile(predicatesDir, predicate, lines);
  fs.mkdirSync(predicatesDir, { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

/**
 * Merges newly generated proposition lines for one predicate into its
 * `predicates/<name>.pl` file: existing facts (from other artists/runs) are
 * preserved, duplicates are removed, and the result is written back
 * whitespace-normalized and sorted so regeneration produces a clean, stable
 * Git diff.
 */
export function mergePredicateFile(
  predicatesDir: string,
  predicate: string,
  newPropositionLines: string[],
): MergeResult {
  const filePath = path.join(predicatesDir, `${predicate}.pl`);
  const existing = readExistingPropositions(filePath);
  const merged = new Set([...existing, ...newPropositionLines]);
  writePropositions(predicatesDir, predicate, merged);

  return {
    predicate,
    file: filePath,
    addedCount: merged.size - existing.length,
    totalCount: merged.size,
  };
}

/** Groups resolved facts by predicate name, preserving deterministic (sorted) order. */
export function groupFactsByPredicate(facts: ResolvedFact[]): Map<string, ResolvedFact[]> {
  const groups = new Map<string, ResolvedFact[]>();
  for (const fact of facts) {
    const group = groups.get(fact.predicate) ?? [];
    group.push(fact);
    groups.set(fact.predicate, group);
  }
  return new Map([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

/**
 * Writes every predicate group into `predicates/`, merging with whatever is
 * already there. Returns one {@link MergeResult} per predicate touched, in
 * deterministic (sorted-by-name) order.
 */
export function writeFactsToPredicates(predicatesDir: string, facts: ResolvedFact[]): MergeResult[] {
  const groups = groupFactsByPredicate(facts);
  const results: MergeResult[] = [];
  for (const [predicate, groupFacts] of groups) {
    const lines = groupFacts.map((f) => factToProposition(f.predicate, f.arguments));
    results.push(mergePredicateFile(predicatesDir, predicate, lines));
  }
  return results;
}
