import * as fs from "node:fs";
import * as path from "node:path";
import type { FactArgument, ResolvedFact } from "./types.js";

/** Renders one typed argument as a BeingDB literal (see docs/query-language.md "Literal types"). */
export function literalToString(arg: FactArgument): string {
  switch (arg.kind) {
    case "atom":
      return arg.value;
    case "string":
      return `"${escapeString(arg.value)}"`;
    case "year":
      return `@${arg.value}`;
    case "integer":
      return String(arg.value);
    case "decimal":
      return arg.value;
    case "boolean":
      return arg.value ? "true" : "false";
  }
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Renders one fact as a single BeingDB proposition line, e.g. `created_by(tape_tape, kevin_atherton).`. */
export function factToProposition(predicate: string, args: FactArgument[]): string {
  return `${predicate}(${args.map(literalToString).join(", ")}).`;
}

const GENERATED_HEADER = (predicate: string) =>
  `% ${predicate} facts generated by beingdb-rewind-interviews (npm run extract).\n` +
  `% See metadata/extraction.json for source provenance and candidates/evidence for supporting quotes.\n` +
  `% Do not hand-edit generated lines below - regenerate and review the diff instead.\n`;

function isDataLine(line: string): boolean {
  const trimmed = line.trim();
  return trimmed.length > 0 && !trimmed.startsWith("%") && !trimmed.startsWith("#");
}

/** Reads the existing data (non-comment) lines of a predicate file, if any. */
export function readExistingPropositions(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  return fs
    .readFileSync(filePath, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(isDataLine);
}

export interface MergeResult {
  predicate: string;
  file: string;
  addedCount: number;
  totalCount: number;
}

/**
 * Merges newly generated proposition lines for one predicate into its
 * `predicates/<name>.pl` file: existing facts (from other artists/runs) are
 * preserved, duplicates are removed, and the result is written back
 * whitespace-normalized and sorted so regeneration produces a clean, stable
 * Git diff.
 */
export function mergePredicateFile(
  predicatesDir: string,
  predicate: string,
  newPropositionLines: string[],
): MergeResult {
  const filePath = path.join(predicatesDir, `${predicate}.pl`);
  const existing = readExistingPropositions(filePath);
  const merged = Array.from(new Set([...existing, ...newPropositionLines])).sort((a, b) => a.localeCompare(b));

  fs.mkdirSync(predicatesDir, { recursive: true });
  fs.writeFileSync(filePath, GENERATED_HEADER(predicate) + merged.join("\n") + "\n", "utf8");

  return {
    predicate,
    file: filePath,
    addedCount: merged.length - existing.length,
    totalCount: merged.length,
  };
}

/** Groups resolved facts by predicate name, preserving deterministic (sorted) order. */
export function groupFactsByPredicate(facts: ResolvedFact[]): Map<string, ResolvedFact[]> {
  const groups = new Map<string, ResolvedFact[]>();
  for (const fact of facts) {
    const group = groups.get(fact.predicate) ?? [];
    group.push(fact);
    groups.set(fact.predicate, group);
  }
  return new Map([...groups.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

/**
 * Writes every predicate group into `predicates/`, merging with whatever is
 * already there. Returns one {@link MergeResult} per predicate touched, in
 * deterministic (sorted-by-name) order.
 */
export function writeFactsToPredicates(predicatesDir: string, facts: ResolvedFact[]): MergeResult[] {
  const groups = groupFactsByPredicate(facts);
  const results: MergeResult[] = [];
  for (const [predicate, groupFacts] of groups) {
    const lines = groupFacts.map((f) => factToProposition(f.predicate, f.arguments));
    results.push(mergePredicateFile(predicatesDir, predicate, lines));
  }
  return results;
}
